In [1]:
from frtorch import LinearChainCRF

# TODO: debug the entropy DP

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch 
import numpy as np

In [4]:
transition = torch.randn([2000, 2000])
emission = torch.randn([1, 10, 2000])
lens = torch.tensor([10])

In [29]:
# This case should be verified and implemented correctly

transition = torch.zeros([2, 2])
emission = torch.zeros([1, 10, 2])
lens = torch.tensor([3])

In [6]:
crf = LinearChainCRF()

In [30]:
alpha, log_Z = crf.forward_sum(transition, emission, lens)

In [31]:
alpha

tensor([[[0.0000, 0.0000],
         [0.6931, 0.6931],
         [1.3863, 1.3863],
         [2.0794, 2.0794],
         [2.7726, 2.7726],
         [3.4657, 3.4657],
         [4.1589, 4.1589],
         [4.8520, 4.8520],
         [5.5452, 5.5452],
         [6.2383, 6.2383]]])

In [32]:
h_total, H = crf.entropy(transition, emission, lens, debug=True)

tensor([[1.3863, 1.3863]])
tensor([[-0.6931, -0.6931]])
tensor([[0.5000, 0.5000]])
tensor([[1.0397, 1.0397]])


In [33]:
h_total

tensor([2.0794])

In [28]:
np.log(8)

2.0794415416798357

In [10]:
-2 * np.log(1/2)

1.3862943611198906

In [11]:
_, log_z = crf.forward_sum(transition, emission, lens)

In [12]:
log_z

tensor([16.0740])

In [14]:
_, log_z = crf.forward_sum(transition, emission, lens, mem_efficient=True)

In [15]:
log_z

tensor([18.6712])

# Test K sample

In [4]:
from collections import Counter

In [12]:
transition = torch.zeros([2, 2]).to('cuda')
emission = torch.zeros([1, 3, 2]).to('cuda')
lens = torch.tensor([2]).to('cuda')

In [19]:
sample, sample_log_prob = crf.ksample(transition, emission, lens, 10000)

In [11]:
sample_log_prob.size()

torch.Size([1, 100000])

In [22]:
samples = []
for s in sample[0]:
    samples.append(str(int(s[0])) + str(int(s[1])) + str(int(s[2])))

In [23]:
samples = Counter(samples)

In [24]:
samples

Counter({'101': 1241,
         '001': 1252,
         '111': 1260,
         '011': 1266,
         '100': 1229,
         '010': 1191,
         '110': 1297,
         '000': 1264})